base:
    seed: &seed 42
model:
    type: Llama
    path: /mnt/nvme0/yongyang/llm_weights/llama2/llama2-7b
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: /mnt/nvme0/yongyang/llm_datasets/llmc/calib/pileval
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: general
    seed: *seed
eval:
    # eval_pos: [pretrain, fake_quant]
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: /mnt/nvme0/yongyang/llm_datasets/llmc/eval/wikitext2
    bs: 1
    inference_per_block: False
    # For 70B model eval, bs can be set to 20, and inference_per_block can be set to True.
    # For 7B / 13B model eval, bs can be set to 1, and inference_per_block can be set to False.
    seq_len: 2048
quant:
    method: Awq
    tp: 2
    weight:
        bit: 2
        symmetric: False
        granularity: per_group
        group_size: 64
    # act:
    #     bit: 4
    #     symmetric: False
    #     granularity: per_token
save:
    save_trans: False
    save_path: ./save/awq_w2a16g64_fakequant_eval_general_llama2-7b_tp2
    tokenizer_file_substring: ["token"]
